# Generated by Django 3.2.16 on 2024-08-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroImagen',
            fields=[
                ('imagen_base_64', models.ImageField(upload_to='images/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroUbicacion',
            fields=[
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
