# Generated by Django 3.2.16 on 2024-08-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_registroimagen_registroubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroimagen',
            name='url',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
