# Generated by Django 3.2.16 on 2024-08-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_registroimagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroimagen',
            name='imagen_base_64',
        ),
        migrations.AddField(
            model_name='registroimagen',
            name='contiene_varroa',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
