# Generated by Django 3.2.16 on 2024-08-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240801_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroimagen',
            name='contiene_varroa',
        ),
    ]
