# Generated by Django 3.2.16 on 2024-08-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_registroimagen_contiene_varroa'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroimagen',
            name='contiene_varroa',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
